services:
  db:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d metrics_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres_backend
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: network_password
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: python_web_api
    ports:
      - "8081:8081"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=1411f532-a6d4-4e86-9400-c98388f6bddd;IngestionEndpoint=https://canadaeast-0.in.applicationinsights.azure.com/;LiveEndpoint=https://canadaeast.livediagnostics.monitor.azure.com/;ApplicationId=f421a0d1-11cc-40a3-a029-759c8d1d1b98
      ACCOUNT_SERVICE_URL: http://p1-web-app-test.azurewebsites.net
      DB_HOST: db
      DB_NAME: metrics_db
      DB_USER: admin_user
      DB_PASSWORD: network_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
